# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lamlai.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.Home)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Home)
        self.Screen1 = QtWidgets.QWidget()
        self.Screen1.setObjectName("Screen1")
        self.label_2 = QtWidgets.QLabel(self.Screen1)
        self.label_2.setGeometry(QtCore.QRect(200, 70, 201, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.Screen1)
        self.Screen2 = QtWidgets.QWidget()
        self.Screen2.setObjectName("Screen2")
        self.label_3 = QtWidgets.QLabel(self.Screen2)
        self.label_3.setGeometry(QtCore.QRect(280, 120, 151, 121))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.Screen2)
        self.Screen3 = QtWidgets.QWidget()
        self.Screen3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Screen3.setObjectName("Screen3")
        self.label_4 = QtWidgets.QLabel(self.Screen3)
        self.label_4.setGeometry(QtCore.QRect(300, 120, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.Screen3)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 4)
        self.Home_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Home_Button.setObjectName("Home_Button")
        self.gridLayout.addWidget(self.Home_Button, 1, 0, 1, 1)
        self.Screen1_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Screen1_Button.setObjectName("Screen1_Button")
        self.gridLayout.addWidget(self.Screen1_Button, 1, 1, 1, 1)
        self.Screen2_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Screen2_Button.setObjectName("Screen2_Button")
        self.gridLayout.addWidget(self.Screen2_Button, 1, 2, 1, 1)
        self.Screen3_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Screen3_Button.setObjectName("Screen3_Button")
        self.gridLayout.addWidget(self.Screen3_Button, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "chính"))
        self.label_2.setText(_translate("MainWindow", "màn hình 1"))
        self.label_3.setText(_translate("MainWindow", "màn hình 2"))
        self.label_4.setText(_translate("MainWindow", "Màn hình 3"))
        self.Home_Button.setText(_translate("MainWindow", "Home"))
        self.Screen1_Button.setText(_translate("MainWindow", "Sreen1"))
        self.Screen2_Button.setText(_translate("MainWindow", "Screen2"))
        self.Screen3_Button.setText(_translate("MainWindow", "Screen3"))
